### PR TITLE
Webhooks support

### PR DESCRIPTION
**Pull request by evserykh**

### CODE REVIEW

**Comment by palkan** [comment]
Let's freeze the Rubocop version. New cops are failing(

```ruby
spec.add_development_dependency "rubocop", "~> 0.49.0"
```

**Comment by evserykh** [comment]
Actually I've nothing done with Rubocop and it's setting 🤔

However I've created one more PR #45 that fixes Rubocop errors and warnings. So I propose merge PR #45 first and after that merge this one. I've checked locally: Rspec and Rubocop are green it that case.

**Comment by evserykh** [comment]
Hi. Should I do something else to have this PR merged?

**Comment by palkan** [comment]
> Should I do something else to have this PR merged?

Nope. Looks good. Thanks!

**Pull request merged**
